use testing;
/*
DROP TABLE IF EXISTS RANDOMNAMES;

CREATE TABLE RANDOMNAMES (
	`Id` int NOT NULL AUTO_INCREMENT primary KEY,
    `Sex` varchar(10),
    `FirstName` varchar(25),
    `LastName` varchar(25)
);
*/
DROP TEMPORARY TABLE IF EXISTS `TMP_FIRST_NAME`;
DROP TEMPORARY TABLE IF EXISTS `TMP_LAST_NAME`;
DROP TEMPORARY TABLE IF EXISTS `TMP_NAME`;
CREATE TEMPORARY TABLE `TMP_FIRST_NAME` (
    `Sex` varchar(10),
    `FirstName` varchar(25));
CREATE TEMPORARY TABLE `TMP_LAST_NAME` (
    `LastName` varchar(25));
CREATE TEMPORARY TABLE `TMP_NAME` (
    `Sex` varchar(10),
    `FirstName` varchar(25),
    `LastName` varchar(25));
    
INSERT TMP_FIRST_NAME ( `Sex`, `FirstName` )
 VALUES
( 'FEMALE', 'Denise' ),
( 'FEMALE', 'Angelina' ),
( 'FEMALE', 'Kayla' ),
( 'FEMALE', 'Mila' ),
( 'FEMALE', 'Rose' ),
( 'FEMALE', 'Makayla' ),
( 'FEMALE', 'Sydnee' ),
( 'FEMALE', 'Ariella' ),
( 'FEMALE', 'Paris' ),
( 'FEMALE', 'Kenley' ),
( 'FEMALE', 'Emilie' ),
( 'FEMALE', 'Lilah' ),
( 'FEMALE', 'Kiera' ),
( 'FEMALE', 'Yoselin' ),
( 'FEMALE', 'Giuliana' ),
( 'FEMALE', 'Anne' ),
( 'FEMALE', 'Averie' ),
( 'FEMALE', 'Jade' ),
( 'FEMALE', 'Callie' ),
( 'FEMALE', 'Camille' ),
( 'FEMALE', 'Nathalia' ),
( 'FEMALE', 'Kiana' ),
( 'FEMALE', 'Melissa' ),
( 'FEMALE', 'Belinda' ),
( 'FEMALE', 'Josie' ),
( 'FEMALE', 'Isabella' ),
( 'FEMALE', 'Jaylynn' ),
( 'FEMALE', 'Cassidy' ),
( 'FEMALE', 'Destiny' ),
( 'FEMALE', 'Aryanna' ),
( 'FEMALE', 'Londyn' ),
( 'FEMALE', 'Kaley' ),
( 'FEMALE', 'Reese' ),
( 'FEMALE', 'Jennifer' ),
( 'FEMALE', 'Felicity' ),
( 'FEMALE', 'Rylee' ),
( 'FEMALE', 'Tanya' ),
( 'FEMALE', 'Bailey' ),
( 'FEMALE', 'Cheyanne' ),
( 'FEMALE', 'Simone' ),
( 'FEMALE', 'Madalyn' ),
( 'FEMALE', 'Angelique' ),
( 'FEMALE', 'Amaris' ),
( 'FEMALE', 'Miley' ),
( 'FEMALE', 'Tori' ),
( 'FEMALE', 'Deanna' ),
( 'FEMALE', 'Judith' ),
( 'FEMALE', 'Jasmine' ),
( 'FEMALE', 'April' ),
( 'FEMALE', 'Margaret' ),
( 'MALE', 'Tyshawn' ),
( 'MALE', 'Dale' ),
( 'MALE', 'Josiah' ),
( 'MALE', 'Yael' ),
( 'MALE', 'Donte' ),
( 'MALE', 'Joaquin' ),
( 'MALE', 'Billy' ),
( 'MALE', 'Aden' ),
( 'MALE', 'Antony' ),
( 'MALE', 'Talon' ),
( 'MALE', 'Zavier' ),
( 'MALE', 'Allan' ),
( 'MALE', 'Maddox' ),
( 'MALE', 'Dorian' ),
( 'MALE', 'Devyn' ),
( 'MALE', 'Darius' ),
( 'MALE', 'Johnny' ),
( 'MALE', 'Elijah' ),
( 'MALE', 'Jake' ),
( 'MALE', 'Jay' ),
( 'MALE', 'Alonzo' ),
( 'MALE', 'Adriel' ),
( 'MALE', 'Andreas' ),
( 'MALE', 'Joe' ),
( 'MALE', 'Coleman' ),
( 'MALE', 'Finnegan' ),
( 'MALE', 'Nick' ),
( 'MALE', 'Case' ),
( 'MALE', 'Riley' ),
( 'MALE', 'Jaydin' ),
( 'MALE', 'Skyler' ),
( 'MALE', 'Markus' ),
( 'MALE', 'Jose' ),
( 'MALE', 'Aedan' ),
( 'MALE', 'Rex' ),
( 'MALE', 'Richard' ),
( 'MALE', 'Tristian' ),
( 'MALE', 'Donavan' ),
( 'MALE', 'Jamie' ),
( 'MALE', 'Thomas' ),
( 'MALE', 'Eduardo' ),
( 'MALE', 'Marlon' ),
( 'MALE', 'Finley' ),
( 'MALE', 'Carlo' ),
( 'MALE', 'Vance' ),
( 'MALE', 'Antoine' ),
( 'MALE', 'Marcos' ),
( 'MALE', 'Omar' ),
( 'MALE', 'Arjun' ),
( 'MALE', 'Noel' );

INSERT TMP_LAST_NAME ( `LastName` )
 VALUES
( 'Mcclain' ),
( 'Velasquez' ),
( 'Roy' ),
( 'Arias' ),
( 'Glover' ),
( 'Mays' ),
( 'Harding' ),
( 'Silva' ),
( 'Sullivan' ),
( 'Mckay' ),
( 'Munoz' ),
( 'Guerrero' ),
( 'Harvey' ),
( 'Caldwell' ),
( 'Landry' ),
( 'Krause' ),
( 'Lynn' ),
( 'Mcdonald' ),
( 'Pennington' ),
( 'Gonzales' ),
( 'Buckley' ),
( 'Rush' ),
( 'Dennis' ),
( 'Wyatt' ),
( 'Beasley' ),
( 'Church' ),
( 'Khan' ),
( 'Shannon' ),
( 'Duffy' ),
( 'Olsen' ),
( 'Boone' ),
( 'Boyer' ),
( 'Perry' ),
( 'Greene' ),
( 'Haas' ),
( 'Newman' ),
( 'Acosta' ),
( 'Santos' ),
( 'Brock' ),
( 'Esparza' ),
( 'Jordan' ),
( 'Berry' ),
( 'Molina' ),
( 'Bird' ),
( 'Dyer' ),
( 'Collins' ),
( 'Watson' ),
( 'Rich' ),
( 'Marsh' ),
( 'Snyder' ),
( 'Taylor' ),
( 'Jennings' ),
( 'Daugherty' ),
( 'Joyce' ),
( 'Li' ),
( 'Schroeder' ),
( 'Rivers' ),
( 'Huynh' ),
( 'Willis' ),
( 'Harrison' ),
( 'Baxter' ),
( 'Keller' ),
( 'Bean' ),
( 'Haney' ),
( 'Terry' ),
( 'Larsen' ),
( 'Newton' ),
( 'Richards' ),
( 'Wilson' ),
( 'Escobar' ),
( 'Farley' ),
( 'Stanton' ),
( 'Meyer' ),
( 'Lamb' ),
( 'Huerta' ),
( 'Duarte' ),
( 'Hahn' ),
( 'Ortega' ),
( 'Patel' ),
( 'Sampson' ),
( 'Mckee' ),
( 'Hartman' ),
( 'Dudley' ),
( 'Vincent' ),
( 'Moody' ),
( 'Mcmahon' ),
( 'Brennan' ),
( 'Durham' ),
( 'Key' ),
( 'Buchanan' ),
( 'Cooke' ),
( 'Blankenship' ),
( 'Fuller' ),
( 'Shepherd' ),
( 'Roberts' ),
( 'Hopkins' ),
( 'Oliver' ),
( 'Klein' ),
( 'Moran' ),
( 'Frederick' );

INSERT TMP_NAME ( `Sex`, `FirstName`, `LastName` )
SELECT 
	`Sex`, 
    `FirstName`,
    ( SELECT `LastName` FROM TMP_LAST_NAME ORDER BY rand() LIMIT 1 ) `LastName`
FROM
	(
	SELECT fn.*
	FROM TMP_FIRST_NAME fn
    ORDER BY rand() LIMIT 100 ) f;

    
INSERT testing.RANDOMNAMES ( `Sex`, `FirstName`, `LastName` )
SELECT t.*
  FROM TMP_NAME t
  LEFT 
  JOIN testing.RANDOMNAMES r
    ON 
    t.`Sex` = r.`Sex` AND 
    t.`FirstName` = r.`FirstName` AND
    t.`LastName` = r.`LastName`
WHERE r.Id IS NULL;