
use testing;

DROP TABLE IF EXISTS RANDOMCOMPANY;

CREATE TABLE RANDOMCOMPANY (
	`Id` int NOT NULL primary KEY,
    `Name` varchar(50),
    `Url` varchar(75)
);

INSERT RANDOMCOMPANY ( `Id`, `Name`, `Url` )
 VALUES
( 1, 'Wal-Mart Stores', 'walmartstores.com' ),
( 2, 'Exxon Mobil', 'exxonmobil.com' ),
( 3, 'General Motors', 'gm.com' ),
( 4, 'Ford Motor', 'ford.com' ),
( 5, 'Enron', 'enron.com' ),
( 6, 'General Electric', 'ge.com' ),
( 7, 'Citigroup', 'citigroup.com' ),
( 8, 'ChevronTexaco', 'chevron.com' ),
( 9, 'Intl. Business Machines', 'ibm.com' ),
( 10, 'Philip Morris', 'philipmorris.com' ),
( 11, 'Verizon Communications', 'verizon.com' ),
( 12, 'American International Group', 'aig.com' ),
( 13, 'American Electric Power', 'aep.com' ),
( 14, 'Duke Energy', 'duke-energy.com' ),
( 15, 'AT&T', 'att.com' ),
( 16, 'Boeing', 'boeing.com' ),
( 17, 'El Paso', 'elpaso.com' ),
( 18, 'Home Depot', 'homedepot.com' ),
( 19, 'Bank of America Corp.', 'bankofamerica.com' ),
( 20, 'Fannie Mae', 'fanniemae.com' ),
( 21, 'J.P. Morgan Chase & Co.', 'jpmorganchase.com' ),
( 22, 'Kroger', 'kroger.com' ),
( 23, 'Cardinal Health', 'cardinal.com' ),
( 24, 'Merck', 'merck.com' ),
( 25, 'State Farm Insurance Cos.', 'statefarm.com' ),
( 26, 'Reliant Energy', 'reliantenergy.com' ),
( 27, 'SBC Communications', 'sbc.com' ),
( 28, 'Hewlett-Packard', 'hp.com' ),
( 29, 'Morgan Stanley Dean Witter', 'msdw.com' ),
( 30, 'Dynegy', 'dynegy.com' ),
( 31, 'McKesson', 'mckesson.com' ),
( 32, 'Sears Roebuck', 'sears.com' ),
( 33, 'Aquila', 'utilicorp.com' ),
( 34, 'Target', 'target.com' ),
( 35, 'Procter & Gamble', 'pg.com' ),
( 36, 'Merrill Lynch', 'ml.com' ),
( 37, 'AOL Time Warner', 'aoltimewarner.com' ),
( 38, 'Albertson''s', 'albertsons.com' ),
( 39, 'Berkshire Hathaway', 'berkshirehathaway.com' ),
( 40, 'Kmart', 'bluelight.com' ),
( 41, 'Freddie Mac', 'freddiemac.com' ),
( 42, 'WorldCom', 'worldcom.com' ),
( 43, 'Marathon Oil', 'marathon.com' ),
( 44, 'Costco Wholesale', 'costco.com' ),
( 45, 'Safeway', 'safeway.com' ),
( 46, 'Compaq Computer', 'compaq.com' ),
( 47, 'Johnson & Johnson', 'jnj.com' ),
( 48, 'Conoco', 'conoco.com' ),
( 49, 'Pfizer', 'pfizer.com' ),
( 50, 'J.C. Penney', 'jcpenney.net' ),
( 51, 'MetLife', 'metlife.com' ),
( 52, 'Mirant', 'mirant.com' ),
( 53, 'Dell Computer', 'dell.com' ),
( 54, 'Goldman Sachs Group', 'gs.com' ),
( 55, 'United Parcel Service', 'ups.com' ),
( 56, 'Motorola', 'motorola.com' ),
( 57, 'Allstate', 'allstate.com' ),
( 58, 'TXU', 'txu.com' ),
( 59, 'United Technologies', 'utc.com' ),
( 60, 'Dow Chemical', 'dow.com' ),
( 61, 'ConAgra', 'conagra.com' ),
( 62, 'Prudential Financial', 'prudential.com' ),
( 63, 'PepsiCo', 'pepsico.com' ),
( 64, 'Wells Fargo', 'wellsfargo.com' ),
( 65, 'Intel', 'intel.com' ),
( 66, 'International Paper', 'ipaper.com' ),
( 67, 'Delphi', 'delphiauto.com' ),
( 68, 'Sprint', 'sprint.com' ),
( 69, 'New York Life Insurance', 'newyorklife.com' ),
( 70, 'E.I. du Pont de Nemours', 'dupont.com' ),
( 71, 'Georgia-Pacific', 'gp.com' ),
( 72, 'Microsoft', 'microsoft.com' ),
( 73, 'Walt Disney', 'disney.com' ),
( 74, 'Aetna', 'aetna.com' ),
( 75, 'Ingram Micro', 'ingrammicro.com' ),
( 76, 'Lucent Technologies', 'lucent.com' ),
( 77, 'Lockheed Martin', 'lockheedmartin.com' ),
( 78, 'Walgreen', 'walgreens.com' ),
( 79, 'Bank One Corp.', 'bankone.com' ),
( 80, 'TIAA-CREF', 'tiaa-cref.org' ),
( 81, 'Phillips Petroleum', 'phillips66.com' ),
( 82, 'BellSouth', 'bellsouth.com' ),
( 83, 'Honeywell International', 'honeywell.com' ),
( 84, 'UnitedHealth Group', 'unitedhealthgroup.com' ),
( 85, 'Viacom', 'viacom.com' ),
( 86, 'Supervalu', 'supervalu.com' ),
( 87, 'PG&E Corp.', 'pgecorp.com' ),
( 88, 'Alcoa', 'alcoa.com' ),
( 89, 'American Express', 'americanexpress.com' ),
( 90, 'Wachovia Corp.', 'wachovia.com' ),
( 91, 'Lehman Brothers Holdings', 'lehman.com' ),
( 92, 'Cisco Systems', 'cisco.com' ),
( 93, 'CVS', 'cvs.com' ),
( 94, 'Lowe''s', 'lowes.com' ),
( 95, 'Sysco', 'sysco.com' ),
( 96, 'Bristol-Myers Squibb', 'bms.com' ),
( 97, 'Electronic Data Systems', 'eds.com' ),
( 98, 'Caterpillar', 'cat.com' ),
( 99, 'Coca-Cola', 'coca-cola.com' ),
( 100, 'Archer Daniels Midland', 'admworld.com' ),
( 101, 'AutoNation', 'autonation.com' ),
( 102, 'Qwest Communications', 'qwest.com' ),
( 103, 'FedEx', 'fedex.com' ),
( 104, 'Mass. Mutual Life Insurance', 'massmutual.com' ),
( 105, 'Pharmacia', 'pharmacia.com' ),
( 106, 'FleetBoston Financial', 'fleet.com' ),
( 107, 'Cigna', 'cigna.com' ),
( 108, 'AMR', 'amrcorp.com' ),
( 109, 'Loews', 'loews.com' ),
( 110, 'Solectron', 'solectron.com' ),
( 111, 'Johnson Controls', 'johnsoncontrols.com' ),
( 112, 'Sun Microsystems', 'sun.com' ),
( 113, 'HCA', 'hcahealthcare.com' ),
( 114, 'Visteon', 'visteon.com' ),
( 115, 'Sara Lee', 'saralee.com' ),
( 116, 'Washington Mutual', 'wamu.com' ),
( 117, 'Tech Data', 'techdata.com' ),
( 118, 'Federated Department Stores', 'federated-fds.com' ),
( 119, 'Raytheon', 'raytheon.com' ),
( 120, 'Xerox', 'xerox.com' ),
( 121, 'U.S. Bancorp', 'usbank.com' ),
( 122, 'TRW', 'trw.com' ),
( 123, 'Abbott Laboratories', 'abbott.com' ),
( 124, 'Northwestern Mutual', 'northwesternmutual.com' ),
( 125, 'UAL', 'united.com' ),
( 126, 'Minnesota Mining & Mfg.', '3m.com' ),
( 127, 'AmerisourceBergen', 'amerisourcebergen.net' ),
( 128, 'Coca-Cola Enterprises', 'cokecce.com' ),
( 129, 'Fleming', 'fleming.com' ),
( 130, 'Emerson Electric', 'gotoemerson.com' ),
( 131, 'Best Buy', 'bestbuy.com' ),
( 132, 'Rite Aid', 'riteaid.com' ),
( 133, 'Publix Super Markets', 'publix.com' ),
( 134, 'Hartford Financial Services', 'thehartford.com' ),
( 135, 'Exelon', 'exeloncorp.com' ),
( 136, 'Nationwide', 'nationwide.com' ),
( 137, 'Xcel Energy', 'xcelenergy.com' ),
( 138, 'Valero Energy', 'valero.com' ),
( 139, 'McDonald''s', 'mcdonalds.com' ),
( 140, 'Weyerhaeuser', 'weyerhaeuser.com' ),
( 141, 'Kimberly-Clark', 'kimberly-clark.com' ),
( 142, 'Liberty Mutual Insurance Group', 'libertymutual.com' ),
( 143, 'May Department Stores', 'maycompany.com' ),
( 144, 'Goodyear Tire & Rubber', 'goodyear.com' ),
( 145, 'Wyeth', 'wyeth.com' ),
( 146, 'Occidental Petroleum', 'oxy.com' ),
( 147, 'Household International', 'household.com' ),
( 148, 'Delta Air Lines', 'delta.com' ),
( 149, 'Gap', 'gap.com' ),
( 150, 'Lear', 'lear.com' ),
( 151, 'Northrop Grumman', 'northropgrumman.com' ),
( 152, 'Amerada Hess', 'hess.com' ),
( 153, 'Halliburton', 'halliburton.com' ),
( 154, 'Deere', 'deere.com' ),
( 155, 'Eastman Kodak', 'kodak.com' ),
( 156, 'CMS Energy', 'cmsenergy.com' ),
( 157, 'Circuit City Stores', 'circuitcity.com' ),
( 158, 'Cinergy', 'cinergy.com' ),
( 159, 'Anheuser-Busch', 'anheuser-busch.com' ),
( 160, 'Winn-Dixie Stores', 'winn-dixie.com' ),
( 161, 'Avnet', 'avnet.com' ),
( 162, 'WellPoint Health Networks', 'wellpoint.com' ),
( 163, 'Sunoco', 'sunocoinc.com' ),
( 164, 'Textron', 'textron.com' ),
( 165, 'Edison International', 'edison.com' ),
( 166, 'General Dynamics', 'gd.com' ),
( 167, 'Tenet Healthcare', 'tenethealth.com' ),
( 168, 'Union Pacific', 'up.com' ),
( 169, 'PacifiCare Health Systems', 'pacificare.com' ),
( 170, 'Farmland Industries', 'farmland.com' ),
( 171, 'Eli Lilly', 'lilly.com' ),
( 172, 'Waste Management', 'wm.com' ),
( 173, 'Office Depot', 'officedepot.com' ),
( 174, 'Williams', 'williams.com' ),
( 175, 'Toys `R` Us', 'toysrus.com' ),
( 176, 'Oracle', 'oracle.com' ),
( 177, 'Tyson Foods', 'tyson.com' ),
( 178, 'Staples', 'staples.com' ),
( 179, 'TJX', 'tjx.com' ),
( 180, 'Dominion Resources', 'dom.com' ),
( 181, 'Computer Sciences', 'csc.com' ),
( 182, 'Manpower', 'manpower.com' ),
( 183, 'Dana', 'dana.com' ),
( 184, 'Anthem', 'anthem.com' ),
( 185, 'Allegheny Energy', 'alleghenyenergy.com' ),
( 186, 'Whirlpool', 'whirlpoolcorp.com' ),
( 187, 'Humana', 'humana.com' ),
( 188, 'Southern', 'southernco.com' ),
( 189, 'Marriott International', 'marriott.com' ),
( 190, 'MBNA', 'mbna.com' ),
( 191, 'Arrow Electronics', 'arrow.com' ),
( 192, 'Health Net', 'health.net' ),
( 193, 'Marsh & McLennan', 'mmc.com' ),
( 194, 'Northwest Airlines', 'nwa.com' ),
( 195, 'Public Service Enterprise Group', 'pseg.com' ),
( 196, 'Schering-Plough', 'schering-plough.com' ),
( 197, 'Illinois Tool Works', 'itw.com' ),
( 198, 'Comcast', 'comcast.com' ),
( 199, 'Consolidated Edison', 'conedison.com' ),
( 200, 'Entergy', 'entergy.com' ),
( 201, 'AES', 'aesc.com' ),
( 202, 'AFLAC', 'aflac.com' ),
( 203, 'NiSource', 'nisource.com' ),
( 204, 'Nike', 'nike.com' ),
( 205, 'UnumProvident', 'unum.com' ),
( 206, 'H.J. Heinz', 'heinz.com' ),
( 207, 'Colgate-Palmolive', 'colgate.com' ),
( 208, 'Limited', 'limited.com' ),
( 209, 'John Hancock Financial Services', 'jhancock.com' ),
( 210, 'Express Scripts', 'express-scripts.com' ),
( 211, 'Burlington Northern Santa Fe', 'bnsf.com' ),
( 212, 'Agilent Technologies', 'agilent.com' ),
( 213, 'National City Corp.', 'nationalcity.com' ),
( 214, 'Fluor', 'fluor.com' ),
( 215, 'United Services Automobile Assn.', 'usaa.com' ),
( 216, 'Continental Airlines', 'continental.com' ),
( 217, 'Cendant', 'cendant.com' ),
( 218, 'St. Paul Cos.', 'stpaul.com' ),
( 219, 'Guardian Life Ins. Co. of America', 'glic.com' ),
( 220, 'Kellogg', 'kelloggs.com' ),
( 221, 'Principal Financial', 'principal.com' ),
( 222, 'SCI Systems', 'sci.com' ),
( 223, 'Bear Stearns', 'bearstearns.com' ),
( 224, 'R.J. Reynolds Tobacco', 'rjrt.com' ),
( 225, 'Ashland', 'ashland.com' ),
( 226, 'FPL Group', 'fplgroup.com' ),
( 227, 'Progress Energy', 'progress-energy.com' ),
( 228, 'Pepsi Bottling', 'pbg.com' ),
( 229, 'SunTrust Banks', 'suntrust.com' ),
( 230, 'Dillard''s', 'dillards.com' ),
( 231, 'Smurfit-Stone Container', 'smurfit-stone.net' ),
( 232, 'Anadarko Petroleum', 'anadarko.com' ),
( 233, 'Masco', 'masco.com' ),
( 234, 'US Airways Group', 'usairways.com' ),
( 235, 'Genuine Parts', 'genpt.com' ),
( 236, 'Texas Instruments', 'ti.com' ),
( 237, 'PPG Industries', 'ppg.com' ),
( 238, 'CSX', 'csx.com' ),
( 239, 'Conseco', 'conseco.com' ),
( 240, 'Gillette', 'gillette.com' ),
( 241, 'Sempra Energy', 'sempra.com' ),
( 242, 'FirstEnergy', 'firstenergycorp.com' ),
( 243, 'Clear Channel Communications', 'clearchannel.com' ),
( 244, 'Cenex Harvest States', 'chsco-ops.com' ),
( 245, 'DTE Energy', 'dteenergy.com' ),
( 246, 'Aramark', 'aramark.com' ),
( 247, 'Aon', 'aon.com' ),
( 248, 'Baxter International', 'baxter.com' ),
( 249, 'Chubb', 'chubb.com' );