//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.json.db.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.json.db.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Aleutians East&quot;,
        ///    &quot;Index&quot;: 10,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Aleutians West&quot;,
        ///    &quot;Index&quot;: 20,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Anchorage&quot;,
        ///    &quot;Index&quot;: 30,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Bethel&quot;,
        ///    &quot;Index&quot;: 40,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string county_list_json {
            get {
                return ResourceManager.GetString("county_list_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: null,
        ///    &quot;Name&quot;: &quot;Alaska&quot;,
        ///    &quot;ShortName&quot;: &quot;AK&quot;,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Id&quot;: null,
        ///    &quot;Name&quot;: &quot;Alabama&quot;,
        ///    &quot;ShortName&quot;: &quot;AL&quot;,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Id&quot;: null,
        ///    &quot;Name&quot;: &quot;Arkansas&quot;,
        ///    &quot;ShortName&quot;: &quot;AR&quot;,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Id&quot;: null,
        ///    &quot;Name&quot;: &quot;American Samoa&quot;,
        ///    &quot;ShortName&quot;: &quot;AS&quot;,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Id&quot;: null,
        ///    &quot;Name&quot;: &quot;Arizona&quot;,
        ///    &quot;ShortName&quot;: &quot;AZ&quot;,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string state_list_json {
            get {
                return ResourceManager.GetString("state_list_json", resourceCulture);
            }
        }
    }
}
