//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace permissions.api.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("permissions.api.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEsDBBQACAgIAJoQEFkVWNoVRwEAAKEEAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbLWUy07DMBBFfyXyFiVuWSCEmnbBYwmVKB9g7Elj1S95pqX9eyYuIISKVES7cpw7c891JvJktvWu2kBGG0Mrxs1IVBB0NDYsW/GyeKivRYWkglEuBmjFDlDMppPFLgFW3BuwFT1RupESdQ9eYRMTBFa6mL0i3ualTEqv1BLk5Wh0JXUMBIFqGjzEdHIHnVo7qm737wfrVqiUnNWKOJZkM1Hdb1ncpxz28oi+TTA/wtQfQZoMrtRgbxNe/ASwigPhiT9Mtgb+hIhdZzWYqNeeWxpMGZTBHoC8a8raeGXDHjpXmR6VZ1e5dfIt5tVrjKumaGcJMCDK82/8IqIsy/iMQZB2DvBQir3yP/TnnHXMUKfMaiZ7AMfh5qyiHApPeloYficD5ig6W58UrtdI0R938FJ6zkH3KoN5psxXyuF5fy/4CiLLFTN9B1BLBwgVWNoV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string denton_excel_file {
            get {
                return ResourceManager.GetString("denton-excel-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEsDBBQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string denton_excel_file_01 {
            get {
                return ResourceManager.GetString("denton-excel-file-01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;requestId&quot;: &quot;e8983cfb-0a68-11ef-99ce-0af7a01f52e9&quot;,
        ///    &quot;request&quot;: {
        ///        &quot;state&quot;: &quot;tx&quot;,
        ///        &quot;county&quot;: {
        ///            &quot;name&quot;: &quot;denton&quot;,
        ///            &quot;value&quot;: 26730
        ///        },
        ///        &quot;details&quot;: [
        ///            {
        ///                &quot;name&quot;: &quot;Court Type&quot;,
        ///                &quot;text&quot;: &quot;All County Courts&quot;,
        ///                &quot;value&quot;: &quot;9&quot;
        ///            },
        ///            {
        ///                &quot;name&quot;: &quot;Case Type&quot;,
        ///                &quot;text&quot;: &quot;JP And County Courts&quot;,
        ///                &quot;value&quot;: &quot;0&quot;
        ///            }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_search_requested_response {
            get {
                return ResourceManager.GetString("sample-search-requested-response", resourceCulture);
            }
        }
    }
}
