//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.permissions.api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.permissions.api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr /&gt;
        ///&lt;h5&gt;Guest&lt;/h5&gt;
        ///&lt;div&gt;
        ///    &lt;p class=&quot;lead&quot;&gt;
        ///        You have a Guest Account. 
        ///        As a Guest you have the following search restrictions.
        ///    &lt;/p&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Searches: A limit of 5 records can returned from any a search.&lt;/li&gt;
        ///        &lt;li&gt;Monthly Limit: A maximum of 15 records can be retrieved in a calendar month.&lt;/li&gt;
        ///        &lt;li&gt;Annual Limit: A maximum of 50 records can be retrieved in a calendar year.&lt;/li&gt;
        ///    &lt;/ol&gt;
        ///    &lt;p&gt;
        ///        Data restriction: 
        ///        Any search res [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string description_role_admin {
            get {
                return ResourceManager.GetString("description-role-admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr /&gt;
        ///&lt;h5&gt;Guest&lt;/h5&gt;
        ///&lt;div&gt;
        ///    &lt;p class=&quot;lead&quot;&gt;
        ///        You have a Guest Account. 
        ///        As a Guest you have the following search restrictions.
        ///    &lt;/p&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Searches: A limit of 5 records can returned from any a search.&lt;/li&gt;
        ///        &lt;li&gt;Monthly Limit: A maximum of 15 records can be retrieved in a calendar month.&lt;/li&gt;
        ///        &lt;li&gt;Annual Limit: A maximum of 50 records can be retrieved in a calendar year.&lt;/li&gt;
        ///    &lt;/ol&gt;
        ///    &lt;p&gt;
        ///        Data restriction: 
        ///        Any search res [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string description_role_gold {
            get {
                return ResourceManager.GetString("description-role-gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr /&gt;
        ///&lt;h5&gt;Guest&lt;/h5&gt;
        ///&lt;div&gt;
        ///    &lt;p class=&quot;lead&quot;&gt;
        ///        You have a Guest Account. 
        ///        As a Guest you have the following search restrictions.
        ///    &lt;/p&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Searches: A limit of 5 records can returned from any a search.&lt;/li&gt;
        ///        &lt;li&gt;Monthly Limit: A maximum of 15 records can be retrieved in a calendar month.&lt;/li&gt;
        ///        &lt;li&gt;Annual Limit: A maximum of 50 records can be retrieved in a calendar year.&lt;/li&gt;
        ///    &lt;/ol&gt;
        ///    &lt;p&gt;
        ///        Data restriction: 
        ///        Any search res [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string description_role_guest {
            get {
                return ResourceManager.GetString("description-role-guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr /&gt;
        ///&lt;h5&gt;Guest&lt;/h5&gt;
        ///&lt;div&gt;
        ///    &lt;p class=&quot;lead&quot;&gt;
        ///        You have a Guest Account. 
        ///        As a Guest you have the following search restrictions.
        ///    &lt;/p&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Searches: A limit of 5 records can returned from any a search.&lt;/li&gt;
        ///        &lt;li&gt;Monthly Limit: A maximum of 15 records can be retrieved in a calendar month.&lt;/li&gt;
        ///        &lt;li&gt;Annual Limit: A maximum of 50 records can be retrieved in a calendar year.&lt;/li&gt;
        ///    &lt;/ol&gt;
        ///    &lt;p&gt;
        ///        Data restriction: 
        ///        Any search res [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string description_role_platinum {
            get {
                return ResourceManager.GetString("description-role-platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr /&gt;
        ///&lt;h5&gt;Guest&lt;/h5&gt;
        ///&lt;div&gt;
        ///    &lt;p class=&quot;lead&quot;&gt;
        ///        You have a Guest Account. 
        ///        As a Guest you have the following search restrictions.
        ///    &lt;/p&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Searches: A limit of 5 records can returned from any a search.&lt;/li&gt;
        ///        &lt;li&gt;Monthly Limit: A maximum of 15 records can be retrieved in a calendar month.&lt;/li&gt;
        ///        &lt;li&gt;Annual Limit: A maximum of 50 records can be retrieved in a calendar year.&lt;/li&gt;
        ///    &lt;/ol&gt;
        ///    &lt;p&gt;
        ///        Data restriction: 
        ///        Any search res [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string description_role_silver {
            get {
                return ResourceManager.GetString("description-role-silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # leads-ui
        ///The ultimate lead sourcing application
        ///
        ///## Components   
        /// - legallead.jsdb : light-weight data store for application meta data
        /// - legallead.permission.api : api provider for user registration, authentication, permissions.
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
    }
}
