//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///* Forms
        ///*/
        ///.form-control {
        ///    background-color: transparent;
        ///    border-color: #555;
        ///    color: ghostwhite;
        ///}
        ///
        ///.form-control.error {
        ///    border-color: red;
        ///}
        ///label.error {
        ///    color: red;
        ///    font-size: small;
        ///}
        ///div.help-text {
        ///    font-size: small;
        ///}
        ///
        ////*
        /// * Header
        /// */
        ///div[name=&quot;header&quot;] {
        ///    height: 50px; 
        ///    border-bottom: #444 solid 1px;
        ///    margin-top: 5px;
        ///}
        ///
        ///
        ////*
        /// * Loader
        /// */
        ///div[name=&quot;loader&quot;] {
        ///  margin-top: 20px;
        ///  margin-bottom: 20px;
        ///  border: 16px soli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_css {
            get {
                return ResourceManager.GetString("base-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///			CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///		&lt;/script&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui&lt;/title&gt;
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///		&lt;!-- bootstrap --&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blank_html {
            get {
                return ResourceManager.GetString("blank-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @charset &quot;UTF-8&quot;;/*!
        /// * Bootstrap  v5.3.2 (https://getbootstrap.com/)
        /// * Copyright 2011-2023 The Bootstrap Authors
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
        /// */:root,[data-bs-theme=light]{--bs-blue:#0d6efd;--bs-indigo:#6610f2;--bs-purple:#6f42c1;--bs-pink:#d63384;--bs-red:#dc3545;--bs-orange:#fd7e14;--bs-yellow:#ffc107;--bs-green:#198754;--bs-teal:#20c997;--bs-cyan:#0dcaf0;--bs-black:#000;--bs-white:#fff;--bs-gray:#6c757d;--bs-gray-dark:#343a40;--bs-gray-100:#f8f9fa;--b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrapmin_css {
            get {
                return ResourceManager.GetString("bootstrapmin-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		try {
        ///			CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///		} catch {}		
        ///	&lt;/script&gt;.
        /// </summary>
        internal static string commoncefhandler_html {
            get {
                return ResourceManager.GetString("commoncefhandler_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///	
        ///	let clientScriptActivated = false;
        ///
        ///	function commonClientScript() {
        ///		try {
        ///			/* user injected block */
        ///		} catch(err) {
        ///			console.debug(err);
        ///		}
        ///	}
        ///	if (clientScriptActivated) {
        ///		setTimeout( () =&gt; { commonClientScript(); }, 250);
        ///	}
        ///	
        ///&lt;/script&gt;.
        /// </summary>
        internal static string commonclientinjection_js {
            get {
                return ResourceManager.GetString("commonclientinjection_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///      &lt;footer class=&quot;mastfoot mt-auto&quot;&gt;
        ///			&lt;div id=&quot;footer-copy&quot; class=&quot;float-end&quot;&gt;
        ///				&lt;span id=&quot;footer-copy-span&quot;&gt;{0}&lt;/span&gt;
        ///			&lt;/div&gt;
        ///			&lt;div id=&quot;footer-reload&quot; class=&quot;float-start&quot;&gt;
        ///				&lt;a id=&quot;footer-reload-link&quot; href=&quot;javascript:reloadContent()&quot; class=&quot;text-secondary text-decoration-none&quot;&gt;Reload&lt;/a&gt;
        ///			&lt;/div&gt;
        ///      &lt;/footer&gt;.
        /// </summary>
        internal static string commonfooter_html {
            get {
                return ResourceManager.GetString("commonfooter_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///		
        ///		&lt;!-- popper --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///		&lt;!-- bootstrap --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css&quot;&gt;
        ///		&lt;link re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commonheadings_html {
            get {
                return ResourceManager.GetString("commonheadings_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		
        ///	function getPageName() {
        ///		const defaultName = &quot;home&quot;;
        ///		const colon = &quot;:&quot;;
        ///		var current_title = $(document).attr(&apos;title&apos;);
        ///		if ( undefined === current_title || null === current_title || current_title.length === 0) return defaultName;
        ///		if (current_title.indexOf(colon) &lt; 0 || current_title.split(colon).length &lt; 2) return defaultName;
        ///		var landing = current_title.split(&apos;:&apos;)[1].trim();
        ///		return landing == &quot;account&quot; ? &quot;myaccount-~0&quot; : &quot;home-~0&quot;;
        ///	}
        ///		
        ///	function getDisplay( ) {
        ///			const fin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commonreload_js {
            get {
                return ResourceManager.GetString("commonreload_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IsVisible&quot;: false,
        ///    &quot;Items&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;Home&quot;,
        ///        &quot;IsDisplayed&quot;: true,
        ///        &quot;IsSelected&quot;: true
        ///      },
        ///      {
        ///        &quot;Name&quot;: &quot;Error&quot;,
        ///        &quot;IsDisplayed&quot;: true,
        ///        &quot;IsSelected&quot;: false
        ///      },
        ///      {
        ///        &quot;Name&quot;: &quot;MyAccount&quot;,
        ///        &quot;IsDisplayed&quot;: false,
        ///        &quot;IsSelected&quot;: false
        ///      }
        ///    ]
        ///  }.
        /// </summary>
        internal static string contextmenu {
            get {
                return ResourceManager.GetString("contextmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: error&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;cover-css&quot; href=&quot;https://getbootstrap.com/docs/4.0/examples/cover/cover.css&quot; /&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error_html {
            get {
                return ResourceManager.GetString("error_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;css/error.css&quot;&gt;
        ///
        ///#errorbox {
        ///    position: relative;
        ///    height: 40vh
        ///}
        ///
        ///#errorbox .errorbox {
        ///    position: absolute;
        ///    left: 50%;
        ///    top: 50%;
        ///    -webkit-transform: translate(-50%,-50%);
        ///    -ms-transform: translate(-50%,-50%);
        ///    transform: translate(-50%,-50%)
        ///}
        ///
        ///.errorbox {
        ///    max-width: 560px;
        ///    width: 100%;
        ///    padding-left: 160px;
        ///    line-height: 1.1
        ///}
        ///
        ///.errorbox .errorbox-callout {
        ///    position: absolute;
        ///    left: 0;
        ///    top: 0;
        ///    display: inline- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errorbox_css {
            get {
                return ResourceManager.GetString("errorbox_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;id&quot;: &quot;500&quot;,
        ///		&quot;isDefault&quot; : true,
        ///		&quot;code&quot;: &quot;Unexpected Error&quot;,
        ///		&quot;description&quot;: [
        ///			&quot;Application encountered an unexpected error. &quot;,
        ///			&quot;Please contact system administrator for additional details or information regarding this error.&quot;
        ///		]
        ///	}, 
        ///	{
        ///		&quot;id&quot;: &quot;503&quot;,
        ///		&quot;code&quot;: &quot;Internet Unavailable&quot;,
        ///		&quot;description&quot;: [
        ///			&quot;Application is unable to connect to internet. &quot;,
        ///			&quot;Please check your internet settings, router, and/or firewall settings &quot;,
        ///			&quot;to resolve this issue.&quot;
        ///		]
        ///	}, 
        ///	{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errorstatus_json {
            get {
                return ResourceManager.GetString("errorstatus_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: home&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; /&gt;
        ///		&lt;style name=&quot;subcontent-css&quot;&gt;
        ///
        ///			div.subcontent {
        ///				width: 50%; 
        ///				min-width: 400px;
        ///				ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_html {
            get {
                return ResourceManager.GetString("home-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;card&quot;&gt;
        ///    &lt;div class=&quot;card-body&quot;&gt;
        ///        &lt;h5 class=&quot;card-title&quot;&gt;Login&lt;/h5&gt;
        ///        &lt;form id=&quot;form-login&quot; name=&quot;form-login&quot;&gt;
        ///            &lt;div class=&quot;mb-3&quot;&gt;
        ///                &lt;label for=&quot;username&quot; class=&quot;form-label&quot;&gt;User Name / Email:&lt;/label&gt;
        ///                &lt;input type=&quot;text&quot; class=&quot;form-control&quot; id=&quot;username&quot; name=&quot;username&quot; aria-describedby=&quot;username-help&quot;&gt;
        ///                &lt;div id=&quot;username-help&quot; class=&quot;text-secondary help-text&quot;&gt;
        ///                    Provide user-name or email address.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homelogin_html {
            get {
                return ResourceManager.GetString("homelogin_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;card&quot;&gt;
        ///    &lt;div class=&quot;card-body&quot;&gt;
        ///        &lt;h5 class=&quot;card-title&quot;&gt;Register&lt;/h5&gt;
        ///        &lt;form id=&quot;form-register&quot; name=&quot;form-register&quot;&gt;
        ///            &lt;div class=&quot;mb-3&quot;&gt;
        ///                &lt;label for=&quot;register-username&quot; class=&quot;form-label&quot;&gt;User Name:&lt;/label&gt;
        ///                &lt;input  type=&quot;text&quot; class=&quot;form-control&quot; 
        ///                        id=&quot;register-username&quot; name=&quot;username&quot; 
        ///                        maxlength=&quot;255&quot; minlength=&quot;8&quot;
        ///                        aria-describedby=&quot;register-username-help [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homeregister_html {
            get {
                return ResourceManager.GetString("homeregister_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///let formNames = [ &quot;form-login&quot;, &quot;form-register&quot; ];
        ///let buttonNames = [ &quot;form-login-submit&quot;, &quot;form-register-submit&quot; ];
        ///var contacticons = {
        ///    spin: &quot;i[name=&apos;message-send-spinner&apos;]&quot;,
        ///    normal: &quot;i[name=&apos;message-send&apos;]&quot;
        ///}
        ///
        ///function isValidEmail( email ) {
        ///	const res = /^(([^&lt;&gt;()\[\]\\.,;:\s@&quot;]+(\.[^&lt;&gt;()\[\]\\.,;:\s@&quot;]+)*)|(&quot;.+&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        ///	return res.test(email.toLowerCase());
        ///}
        ///function initializeValidator() {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homevalidation_js {
            get {
                return ResourceManager.GetString("homevalidation_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///                &lt;br/&gt;
        ///                &lt;p&gt;
        ///					Legal Lead is an application used to locate public data from county courts.
        ///				&lt;/p&gt;
        ///				&lt;p&gt;
        ///					From this application you can retrieve: &lt;br /&gt;
        ///				&lt;/p&gt;
        ///				&lt;div name=&quot;subcontent-home-bullet-list&quot; class=&quot;text-left&quot;&gt;
        ///					&lt;ol&gt;
        ///						&lt;li&gt;Case Details&lt;/li&gt;
        ///						&lt;li&gt;Defendant Information&lt;/li&gt;
        ///						&lt;li&gt;Court Information&lt;/li&gt;
        ///					&lt;/ol&gt;
        ///				&lt;/div&gt;
        ///                &lt;div name=&quot;page-call-to-action&quot;&gt;
        ///					&lt;p&gt;
        ///						&lt;a href=&quot;javascript:setDisplay(&apos;lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homewelcome_html {
            get {
                return ResourceManager.GetString("homewelcome_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///			CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///		&lt;/script&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: introduction&lt;/title&gt;
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///		&lt;!-- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string introduction_html {
            get {
                return ResourceManager.GetString("introduction-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;subcontent-css&quot;&gt;
        ///
        ///div.subcontent {
        ///	width: 50%; 
        ///	min-width: 400px;
        ///	max-width: 1200px;
        ///    margin-bottom: 20px;
        ///	display: none;
        ///}
        ///			
        ///div.subcontent.active {
        ///	display: block;
        ///}
        ///
        ///div[name=&quot;subcontent-home-bullet-list&quot;] {
        ///	width: 50%; 
        ///	margin-left: 35%;
        ///	text-align: left;
        ///	justify-content: left;
        ///}
        ///			
        ///
        ///div[name=&quot;main-content&quot;] {
        ///	width: 70%; 
        ///	min-width: 800px;
        ///	max-width: 1200px;
        ///}		
        ///
        ///div[name=&quot;subcontent-home&quot;],
        ///div[name=&quot;subcontent-profile&quot;],
        ///div[name=&quot;subconten [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_css {
            get {
                return ResourceManager.GetString("myaccount_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: account&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; /&gt;
        ///		&lt;!-- style: my-account-subcontent-css --&gt;
        ///	&lt;/head&gt;
        ///
        ///	&lt;body class=&quot;text-center&quot;&gt;
        ///
        ///    &lt;div cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_html {
            get {
                return ResourceManager.GetString("myaccount-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-password&quot; name=&quot;subcontent-password&quot; class=&quot;subcontent card&quot;&gt;
        ///                        &lt;div id=&quot;dv-subcontent-password-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-password-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;svg class=&quot;bi flex-shrink-0 me-2&quot; role=&quot;img&quot; aria-label=&quot;Success:&quot;&gt;&lt;use xlink:href=&quot;#check-circle-fill&quot;/&gt;&lt;/svg&gt;
        ///								&lt;div&gt;
        ///								Your account information has been updated successfully
        ///								&lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_password_html {
            get {
                return ResourceManager.GetString("myaccount_password_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let permissions_data = {
        /// &quot;group_panel&quot;: &quot;#dv-subcontent-permissions&quot;,
        /// &quot;change_panel&quot;: &quot;#dv-subcontent-password&quot;,
        /// &quot;cbox&quot;: &quot;#cbo-permissions-group&quot;,
        /// &quot;password_shown&quot;: function() {
        ///	let backup = $(&quot;#account-user-name&quot;).text();
        ///	let currentName = $(&quot;#account-password-username&quot;).val();
        ///	if ( null != currentName &amp;&amp; currentName.trim().length &gt; 2 ) { return; }
        ///	$(&quot;#account-password-username&quot;).val(backup);
        /// },
        /// &quot;discounts&quot;: function() {
        ///		let isContentVisible = $( permissions_data.group_panel ).is(&quot;:v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_permissions_validation_js {
            get {
                return ResourceManager.GetString("myaccount_permissions_validation_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///let profileAlertTimer = null;
        ///let profileNames = [ &quot;frm-profile-address&quot;, &quot;frm-profile-personal&quot;, &quot;frm-profile-phone&quot;, &quot;frm-profile-email&quot; ];
        ///let profileButtonName = &quot;frm-profile-submit-button&quot;;
        ///let profileStatusDiv = &quot;frm-profile-error-message&quot;;
        ///var profileicons = {
        ///    spin: &quot;#form-profile-icon-spin&quot;,
        ///    normal: &quot;#form-profile-icon&quot;
        ///}
        ///
        ///function setSuccessAlert( isActive ) {
        ///	const hddn = &quot;d-none&quot;;
        ///	const parentDv = &quot;#dv-subcontent-profile-row-00&quot;;
        ///	const alertDv = &quot;#dv-subcontent-pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_profile_validation_js {
            get {
                return ResourceManager.GetString("myaccount_profile_validation_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///	const actv = &quot;active&quot;;
        ///	const names = [ &quot;home&quot;, &quot;profile&quot;, &quot;permissions&quot;, &quot;password&quot; ];
        ///
        ///	function setDisplay( name ) {
        ///			if (names.indexOf( name ) &lt; 0 ) { return; }
        ///			setActiveDiv(name);
        ///			const themenu = document.getElementById(&quot;masthead-nav-menu&quot;);
        ///			let thelinks = themenu.getElementsByTagName(&quot;a&quot;);
        ///
        ///			for(let i = 0; i &lt; thelinks.length; i++) {
        ///				let a = thelinks[i];
        ///				const aname = a.getAttribute(&quot;name&quot;);
        ///				if (null === aname || undefined === aname) { continue; }
        ///				i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_script_js {
            get {
                return ResourceManager.GetString("myaccount_script_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-home&quot; name=&quot;subcontent-home&quot; class=&quot;subcontent active card&quot;&gt;
        ///						&lt;div class=&quot;card-body&quot;&gt;
        ///							&lt;h5 class=&quot;card-title&quot;&gt;Account Details&lt;/h5&gt;	
        ///							&lt;div class=&quot;row&quot;&gt;
        ///								&lt;div class=&quot;col-4 text-info text-start&quot;&gt;User Name:&lt;/div&gt;
        ///								&lt;div class=&quot;col-1 text-info&quot;&gt;&lt;/div&gt;
        ///								&lt;div id=&quot;account-user-name&quot; class=&quot;col-7 text-secondary text-start&quot;&gt; - &lt;/div&gt;
        ///							&lt;/div&gt;
        ///							&lt;div class=&quot;row&quot;&gt;
        ///								&lt;div class=&quot;col-4 text-info text-start&quot;&gt;Email:&lt;/div&gt;
        ///								&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccounthome_html {
            get {
                return ResourceManager.GetString("myaccounthome-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-permissions&quot; name=&quot;subcontent-permissions&quot; class=&quot;subcontent card&quot;&gt;
        ///                        &lt;div id=&quot;dv-subcontent-permissions-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-permissions-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;svg class=&quot;bi flex-shrink-0 me-2&quot; role=&quot;img&quot; aria-label=&quot;Success:&quot;&gt;&lt;use xlink:href=&quot;#check-circle-fill&quot;/&gt;&lt;/svg&gt;
        ///								&lt;div&gt;
        ///								Your account information has been updated successfully        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccountpermissions_html {
            get {
                return ResourceManager.GetString("myaccountpermissions-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-profile&quot; name=&quot;subcontent-profile&quot; class=&quot;subcontent card&quot;&gt;
        ///						&lt;div id=&quot;dv-subcontent-profile-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-profile-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;svg class=&quot;bi flex-shrink-0 me-2&quot; role=&quot;img&quot; aria-label=&quot;Success:&quot;&gt;&lt;use xlink:href=&quot;#check-circle-fill&quot;/&gt;&lt;/svg&gt;
        ///								&lt;div&gt;
        ///								Your account information has been updated successfully
        ///								&lt;/div&gt;
        ///							&lt;/div&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccountprofile_html {
            get {
                return ResourceManager.GetString("myaccountprofile-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;subcontent-css&quot;&gt;
        ///
        ///			div.subcontent {
        ///				width: 50%; 
        ///				min-width: 400px;
        ///				max-width: 1200px;
        ///                margin-bottom: 20px;
        ///				display: none;
        ///			}
        ///			
        ///			div.subcontent.active {
        ///				display: block;
        ///			}
        ///
        ///			div[name=&quot;subcontent-home-bullet-list&quot;] {
        ///				width: 50%; 
        ///				margin-left: 35%;
        ///				text-align: left;
        ///				justify-content: left;
        ///			}
        ///			
        ///
        ///			div[name=&quot;main-content&quot;] {
        ///				width: 70%; 
        ///				min-width: 800px;
        ///				max-width: 1200px;
        ///			}		
        ///
        ///			div[nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string subcontent_css {
            get {
                return ResourceManager.GetString("subcontent_css", resourceCulture);
            }
        }
    }
}
