//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Globals
        /// */
        ///
        ////* Links */
        ///a,
        ///a:focus,
        ///a:hover {
        ///  color: #fff;
        ///}
        ///
        ////* Custom default button */
        ///.btn-secondary,
        ///.btn-secondary:hover,
        ///.btn-secondary:focus {
        ///  color: #333;
        ///  text-shadow: none; /* Prevent inheritance from `body` */
        ///  background-color: #fff;
        ///  border: .05rem solid #fff;
        ///}
        ///
        ///
        ////*
        /// * Base structure
        /// */
        ///
        ///html,
        ///body {
        ///  height: 100%;
        ///  background-color: #333;
        ///}
        ///
        ///body {
        ///  display: -ms-flexbox;
        ///  display: -webkit-box;
        ///  display: flex;
        ///  -ms-flex-pack: center;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_css {
            get {
                return ResourceManager.GetString("base-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @charset &quot;UTF-8&quot;;/*!
        /// * Bootstrap  v5.3.2 (https://getbootstrap.com/)
        /// * Copyright 2011-2023 The Bootstrap Authors
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
        /// */:root,[data-bs-theme=light]{--bs-blue:#0d6efd;--bs-indigo:#6610f2;--bs-purple:#6f42c1;--bs-pink:#d63384;--bs-red:#dc3545;--bs-orange:#fd7e14;--bs-yellow:#ffc107;--bs-green:#198754;--bs-teal:#20c997;--bs-cyan:#0dcaf0;--bs-black:#000;--bs-white:#fff;--bs-gray:#6c757d;--bs-gray-dark:#343a40;--bs-gray-100:#f8f9fa;--b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrapmin_css {
            get {
                return ResourceManager.GetString("bootstrapmin-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;legallead.ui: home&lt;/title&gt;
        ///    &lt;!-- googleapis : fonts --&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;!-- bootstrap --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;bootstrap.min.css&quot; /&gt;
        ///    &lt;!-- jquery --&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_html {
            get {
                return ResourceManager.GetString("home-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;legallead.ui: introduction&lt;/title&gt;
        ///    &lt;!-- googleapis : fonts --&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;!-- bootstrap --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;bootstrap.min.css&quot; /&gt;
        ///    &lt;!-- jquery - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string introduction_html {
            get {
                return ResourceManager.GetString("introduction-html", resourceCulture);
            }
        }
    }
}
