//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.email.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.email.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;server&quot;: &quot;db-lead-restored.cmmu8tkizri9.us-east-2.rds.amazonaws.com&quot;,
        ///&quot;name&quot;: &quot;defaultdb&quot;,
        ///&quot;code&quot;: &quot;m/1Ata5kMzR+oEX0y8RHgOvav+k4LuEIbnSJDbhA2G5pMywLOb3eBufnQzSEN+ef&quot;,
        ///&quot;key&quot;: &quot;CDODj4oxaiJKcKJEIBHnHw==&quot;
        ///}.
        /// </summary>
        internal static string db_settings {
            get {
                return ResourceManager.GetString("db-settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;title&gt;Legal Lead Emails&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div id=&quot;email&quot; style=&quot;width:750px; border: 1px black solid; margin: 5px; padding: 5px; font-family: Arial; font-size: 12px&quot;&gt;
        ///
        ///
        ///        &lt;table name=&quot;header&quot; role=&quot;presentation&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///            &lt;tr style=&quot;border-bottom-style: dashed&quot;&gt;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_template_html {
            get {
                return ResourceManager.GetString("email-template-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Account Registration Completed&lt;/h3&gt;
        ///&lt;p&gt;
        ///	Thank you for registering your account with Legal Leads.
        ///	Please make note of these account registration details
        ///&lt;p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;
        ///		Email Address: &lt;!-- Email Address --&gt;
        ///	&lt;/li&gt;
        ///	&lt;li&gt;
        ///		User Name: &lt;!-- User Name --&gt;
        ///	&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string email_template_html_body_account_registered {
            get {
                return ResourceManager.GetString("email_template_html_body_account_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;account&quot;:  &quot;ses-smtp-user.legallead.2024.04&quot;,
        ///    &quot;type&quot;:  &quot;aws-ses&quot;,
        ///    &quot;uid&quot;:  &quot;&quot;,
        ///    &quot;secret&quot;:  &quot;&quot;,
        ///    &quot;settings&quot;:  {
        ///                     &quot;port&quot;:  587,
        ///                     &quot;endpoint&quot;:  &quot;email-smtp.us-east-2.amazonaws.com&quot;,
        ///                     &quot;from&quot;:  {
        ///                                  &quot;email&quot;:  &quot;admin@legallead.co&quot;,
        ///                                  &quot;display&quot;:  &quot;Legal Lead Admin&quot;
        ///                              }
        ///                 }
        ///}.
        /// </summary>
        internal static string smtp_settings {
            get {
                return ResourceManager.GetString("smtp-settings", resourceCulture);
            }
        }
    }
}
