//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.integration.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("db.integration.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;UserName&quot;: &quot;app.testing.account&quot;,
        ///	&quot;Phrase&quot;: &quot;if.we.index.the.array,.w&quot;,
        ///	&quot;Vector&quot;: &quot;4Tb/Abv3Nj/JMKdrae3+QA==&quot;,
        ///	&quot;Token&quot;: &quot;TzhoNCKeJDC1zgTJCxGl58jlhXqedEcRX7MwxMP5BGEJuf3Y2m1JL3Z+jOaV2kw1&quot;,
        ///	&quot;CreateDate&quot;: null,
        ///	&quot;Email&quot;: null,
        ///	&quot;InsertFieldList&quot;: [
        ///		&quot;UserName&quot;,
        ///		&quot;Phrase&quot;,
        ///		&quot;Vector&quot;,
        ///		&quot;Token&quot;,
        ///		&quot;CreateDate&quot;,
        ///		&quot;Email&quot;,
        ///		&quot;Id&quot;
        ///	],
        ///	&quot;UpdateFieldList&quot;: [
        ///		&quot;UserName&quot;,
        ///		&quot;Phrase&quot;,
        ///		&quot;Vector&quot;,
        ///		&quot;Token&quot;,
        ///		&quot;CreateDate&quot;,
        ///		&quot;Email&quot;,
        ///		&quot;Id&quot;
        ///	],
        ///	&quot;Id&quot;: &quot;4411c3b7-a44d-11ef-99ce-0af7a0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string change_password_test {
            get {
                return ResourceManager.GetString("change-password-test", resourceCulture);
            }
        }
    }
}
