//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.installer.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.installer.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing available versions for legallead applications.
        /// - 3.2.16: Sunday, June 9, 2024
        ///     -- 172738188: legallead.desktop-windows 3.2.16
        /// - 3.2.15: Wednesday, June 5, 2024
        ///     -- 171947214: legallead.desktop-windows 3.2.15
        /// - 3.2.14: Tuesday, June 4, 2024
        ///     -- 171845370: legallead.desktop-windows 3.2.14
        /// - 3.2.13: Thursday, May 30, 2024
        ///     -- 170841144: legallead.desktop-windows 3.2.13
        /// - 3.2.12: Sunday, May 26, 2024
        ///     -- 170203403: legallead.desktop-windows 3.2.12
        /// - 3.2.11: Wednesday [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_available {
            get {
                return ResourceManager.GetString("sample-available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing installed versions for legallead applications.
        /// - legallead.desktop-windows
        ///     -- 3.2.16 Sunday, June 9, 2024
        ///     -- 3.2.15 Wednesday, June 5, 2024
        ///     -- 3.2.13 Saturday, June 1, 2024
        ///     -- 3.2.12 Tuesday, May 28, 2024
        /// - legallead.reader.service
        ///     -- v3.2.6 Sunday, June 9, 2024.
        /// </summary>
        internal static string sample_installed {
            get {
                return ResourceManager.GetString("sample-installed", resourceCulture);
            }
        }
    }
}
