/* 
	DB ROLLBACK PROCESS
    REMOVES TABLES IN CORRECT SEQUENCE TO AVOID CONSTRAINTS
    REMOVES PROCS
*/
-- TABLES --
DROP TABLE IF EXISTS CONTENTLINE;
DROP TABLE IF EXISTS CONTENT;

-- PROCS --
DROP PROCEDURE USP_CREATE_CONTENT_REVISION;
DROP PROCEDURE USP_SET_CURRENT_REVISION;