//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.search.api.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.search.api.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;CSS/PublicAccess.css&quot;&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot; style=&quot;table-layout: fixed; margin:0px; padding:0px;&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:PublicAccessUser=&quot;urn:PublicAccessUser&quot;&gt;&lt;tr&gt;&lt;td class=&quot;ssHeaderTitleBanner&quot;&gt;Criminal Case Records Search Results&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tx_denton_criminal_search_result {
            get {
                return ResourceManager.GetString("tx-denton-criminal-search-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;CSS/PublicAccess.css&quot;&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot; style=&quot;table-layout: fixed; margin:0px; padding:0px;&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:PublicAccessUser=&quot;urn:PublicAccessUser&quot;&gt;&lt;tr&gt;&lt;td class=&quot;ssHeaderTitleBanner&quot;&gt;District Clerk Civil, Family Case Records Search Results &lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;table cellspacing=&quot;0&quot; cell [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tx_denton_district_search_result {
            get {
                return ResourceManager.GetString("tx-denton-district-search-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;CSS/PublicAccess.css&quot;&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; border=&quot;0&quot; style=&quot;table-layout: fixed; margin:0px; padding:0px;&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:PublicAccessUser=&quot;urn:PublicAccessUser&quot;&gt;&lt;tr&gt;&lt;td class=&quot;ssHeaderTitleBanner&quot;&gt;Civil, Family &amp;amp; Probate Case Records Search Results&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;table cellspacing=&quot;0&quot; cellpa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tx_denton_normal_search_result {
            get {
                return ResourceManager.GetString("tx-denton-normal-search-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;CSS/PublicAccess.css&quot;&gt;
        ///  
        ///  
        ///  &lt;script language=&quot;javascript&quot;&gt;
        ///
        ///    function AddHiddenFormElement(form, name, value) {
        ///      var hiddenField = document.createElement(&quot;input&quot;);
        ///      hiddenField.setAttribute(&quot;type&quot;, &quot;hidden&quot;);
        ///      hiddenField.setAttribute(&quot;name&quot;, name);
        ///      hiddenField.setAttribute(&quot;value&quot;, value);
        ///      form.appendChild(hiddenField);
        ///    }
        ///
        ///    function LaunchSearch(sPartialQueryString, bNodeSelectorHidde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tx_denton_person_principal {
            get {
                return ResourceManager.GetString("tx_denton_person_principal", resourceCulture);
            }
        }
    }
}
