//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legallead.records.search.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legallead.records.search.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* find the defendant, principal
        ///*/
        ///
        ///
        ///  
        ///function getAddressNode() {
        ///	let arr = [];
        ///	let keywords = [ &quot;defendant&quot;, &quot;principal&quot;, &quot;petitioner&quot;, &quot;applicant&quot;, &quot;claimant&quot;, &quot;decedent&quot; ];
        ///	let headings = document.getElementsByTagName(&quot;th&quot;);
        ///	for(let n = 0; n &lt; headings.length; n++) {
        ///		let hdr = headings[n];
        ///		let attr = hdr.getAttribute(&quot;class&quot;);
        ///		if(undefined == attr || null == attr || attr.indexOf(&quot;ssTableHeader&quot;) &lt; 0 ) continue;
        ///		let rspan = hdr.getAttribute(&quot;rowspan&quot;);
        ///		if(undefined == rsp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string include_denton_tx_get_address_json {
            get {
                return ResourceManager.GetString("include_denton_tx_get_address_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	get denton case style
        /// */
        /// function customTrim(data) {
        ///	const colon = &apos;:&apos;;
        ///	if( data.indexOf(colon) &lt; 0 ) return data;
        ///	const arr = [];
        ///	const items = data.split(colon);
        ///	for (let i = 0; i &lt; items.length; i++) {
        ///		let needsColon = i % 2 == 0;
        ///		let datum = items[i].replace(/\s/g, &apos; &apos;).trim() + (needsColon ? colon : &quot;&quot;);
        ///		arr.push(datum);
        ///	}
        ///	return arr.join(&quot; &quot;);
        /// }
        /// function getPageType() {
        ///	let tbl = document.getElementsByTagName(&quot;table&quot;)[0];
        ///	let txt = tbl.rows[0].cells[0].innerText [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string include_denton_tx_get_case_list_and_heading {
            get {
                return ResourceManager.GetString("include_denton_tx_get_case_list_and_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;search&gt;
        ///  &lt;parameters&gt;
        ///    &lt;parameter name=&quot;Website&quot; /&gt;
        ///    &lt;parameter name=&quot;StartDate&quot; /&gt;
        ///    &lt;parameter name=&quot;EndDate&quot; /&gt;
        ///    &lt;parameter name=&quot;SearchDate&quot; /&gt;
        ///    &lt;parameter name=&quot;SearchComplete&quot;&gt;false&lt;/parameter&gt;
        ///  &lt;/parameters&gt;
        ///  &lt;!-- Name	Zip	Address1	Address2	Address3 --&gt;
        ///  &lt;results&gt;
        ///    &lt;result name=&quot;casedata&quot;&gt;
        ///      &lt;![CDATA[
        ///      ]]&gt;
        ///    &lt;/result&gt;
        ///    &lt;result name=&quot;peopledata&quot;&gt;
        ///      &lt;![CDATA[
        ///      ]]&gt;
        ///    &lt;/result&gt;
        ///    &lt;result name=&quot;perso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_caselayout_xml {
            get {
                return ResourceManager.GetString("xml-caselayout-xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dropDowns&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;criminal courts&quot;,
        ///      &quot;query&quot;: &quot;#sbxControlID2&quot;,
        ///      &quot;options&quot;: [
        ///        {
        ///          &quot;id&quot;: 0,
        ///          &quot;name&quot;: &quot;criminal case records&quot;,
        ///          &quot;query&quot;: &quot;#divOption1 &gt; a&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;probate case records&quot;,
        ///          &quot;query&quot;: &quot;#divOption2 &gt; a&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;magistrate case records&quot;,
        ///          &quot;query&quot;: &quot;#divOption3 &gt; a&quot;
        ///        },
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_collinCountyCaseType_json {
            get {
                return ResourceManager.GetString("xml-collinCountyCaseType-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steps&quot;: [
        ///    {
        ///      &quot;actionName&quot;: &quot;navigate&quot;,
        ///      &quot;displayName&quot;: &quot;open-website-base-uri&quot;,
        ///      &quot;wait&quot;: 1200,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;page&quot;,
        ///        &quot;query&quot;: &quot;https://cijspub.co.collin.tx.us/SecurePA/login.aspx&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;actionName&quot;: &quot;login&quot;,
        ///      &quot;displayName&quot;: &quot;login-to-website&quot;,
        ///      &quot;expectedValue&quot;: &quot;collinCountyUserMap&quot;,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;css&quot;,
        ///        &quot;query&quot;: &quot;#UserName | #Password&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;actionName [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_collinCountyMapping_1_json {
            get {
                return ResourceManager.GetString("xml-collinCountyMapping-1-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;courtLocations&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;1&quot;,
        ///      &quot;courts&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;default&quot;,
        ///          &quot;address&quot;: &quot;&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;County Court At Law #1&quot;,
        ///          &quot;fullName&quot;: &quot;County Court at Law 1&quot;,
        ///          &quot;address&quot;: &quot;210 South Woodrow Lane Denton, TX 76205-6304&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;County Court At Law #2&quot;,
        ///          &quot;fullName&quot;: &quot;County Court at Law 2&quot;,
        ///          &quot;address&quot;: &quot;1451 East McKinney Street, Denton TX 76209-4524&quot;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_courtAddress_json {
            get {
                return ResourceManager.GetString("xml-courtAddress-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;SearchSetting&quot;: {
        ///    &quot;CountySearchTypeId&quot;: 0,
        ///    &quot;CountyCourtId&quot;: 0,
        ///    &quot;DistrictCourtId&quot;: 0,
        ///    &quot;DistrictSearchTypeId&quot;: 0
        ///  }
        ///}.
        /// </summary>
        internal static string xml_denton_settings_json {
            get {
                return ResourceManager.GetString("xml-denton-settings-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;NavInstructions&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;DateFiled&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;FriendlyName&quot;: &quot;Filing-Date-Selection&quot;,
        ///      &quot;Value&quot;: &quot;td[3]/div[1]&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Case&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;FriendlyName&quot;: &quot;Case-Number-Selection&quot;,
        ///      &quot;Value&quot;: &quot;td[1]/a&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Court&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;FriendlyName&quot;: &quot;Court-Name-Selection&quot;,
        ///      &quot;Value&quot;: &quot;td[3]/div[2]&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;CaseType&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;Frien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_dentonCaseCustomInstruction_1_json {
            get {
                return ResourceManager.GetString("xml-dentonCaseCustomInstruction-1-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;NavInstructions&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;DateFiled&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;FriendlyName&quot;: &quot;Filing-Date-Selection&quot;,
        ///      &quot;Value&quot;: &quot;td[4]/div[1]&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Case&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;FriendlyName&quot;: &quot;Case-Number-Selection&quot;,
        ///      &quot;Value&quot;: &quot;td[1]/a&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Court&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;FriendlyName&quot;: &quot;Court-Name-Selection&quot;,
        ///      &quot;Value&quot;: &quot;td[4]/div[2]&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;CaseType&quot;,
        ///      &quot;By&quot;: &quot;XPath&quot;,
        ///      &quot;Frien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_dentonCaseCustomInstruction_json {
            get {
                return ResourceManager.GetString("xml-dentonCaseCustomInstruction-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dropDowns&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;criminal courts&quot;,
        ///      &quot;query&quot;: &quot;#sbxControlID2&quot;,
        ///      &quot;options&quot;: [
        ///        {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;All JP And County Courts&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;All JP Courts&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 3,
        ///          &quot;name&quot;: &quot;Justice of the Peace Pct #1&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 4,
        ///          &quot;name&quot;: &quot;Justice of the Peace Pct #2&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 5, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_dentonCountyCaseType_json {
            get {
                return ResourceManager.GetString("xml-dentonCountyCaseType-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dropDowns&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;criminal courts&quot;,
        ///      &quot;query&quot;: &quot;#sbxControlID2&quot;,
        ///      &quot;options&quot;: [
        ///        {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;All District Courts&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;16th Judicial District Court&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 3,
        ///          &quot;name&quot;: &quot;158th Judicial District Court&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 4,
        ///          &quot;name&quot;: &quot;211th Judicial District Court&quot;
        ///        },
        ///        {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_dentonDistrictCaseType_json {
            get {
                return ResourceManager.GetString("xml-dentonDistrictCaseType-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;SearchSetting&quot;: {
        ///    &quot;CountySearchTypeId&quot;: 0,
        ///    &quot;CountyCourtId&quot;: 0,
        ///    &quot;DistrictCourtId&quot;: 0,
        ///    &quot;DistrictSearchTypeId&quot;: 0
        ///  }
        ///}.
        /// </summary>
        internal static string xml_harris_civil_settings_json {
            get {
                return ResourceManager.GetString("xml-harris-civil-settings-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dropDowns&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;COUNTY CIVIL COURTS&quot;,
        ///      &quot;query&quot;: &quot;#ctl00_ContentPlaceHolder1_ddlCourt&quot;,
        ///      &quot;options&quot;: [
        ///        {
        ///          &quot;id&quot;: 0,
        ///          &quot;name&quot;: &quot;All&quot;,
        ///          &quot;query&quot;: &quot;#divOption1 &gt; a&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;1&quot;,
        ///          &quot;query&quot;: &quot;#divOption2 &gt; a&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;2&quot;,
        ///          &quot;query&quot;: &quot;#divOption3 &gt; a&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 3,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_harrisCivilCaseType_json {
            get {
                return ResourceManager.GetString("xml-harrisCivilCaseType-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steps&quot;: [
        ///    {
        ///      &quot;actionName&quot;: &quot;navigate&quot;,
        ///      &quot;displayName&quot;: &quot;open-website-base-uri&quot;,
        ///      &quot;wait&quot;: 1200,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;page&quot;,
        ///        &quot;query&quot;: &quot;https://www.cclerk.hctx.net/Applications/WebSearch/CourtSearch.aspx?CaseType=Civil&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;actionName&quot;: &quot;jquery-set-selected-index&quot;,
        ///      &quot;displayName&quot;: &quot;court-drop-down list&quot;,
        ///      &quot;expectedValue&quot;: &quot;1&quot;,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;css&quot;,
        ///        &quot;query&quot;: &quot;#ctl00_ContentPlaceHolder1_d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_harrisCivilMapping_json {
            get {
                return ResourceManager.GetString("xml-harrisCivilMapping-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;settings&gt;
        ///  &lt;setting name=&quot;Websites&quot;&gt;
        ///    &lt;keys id=&quot;1&quot; name=&quot;Denton County&quot;&gt;
        ///      &lt;key name=&quot;baseUri&quot;&gt;&lt;![CDATA[http://justice1.dentoncounty.com/PublicAccess/Search.aspx]]&gt;&lt;/key&gt;
        ///      &lt;key name=&quot;query&quot;&gt;&lt;![CDATA[ID=200&amp;NodeID=1251,1252,1253,1254,1255,1256,1260,1270,1280,1265&amp;NodeDesc=------%20All%20District%20Courts%20------]]&gt;&lt;/key&gt;
        ///      &lt;key name=&quot;hlinkUri--inactive&quot;&gt;&lt;![CDATA[http://justice1.dentoncounty.com/PublicAccessDC/]]&gt;&lt;/key&gt;
        ///      &lt;key name=&quot;dateRan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_settings_xml {
            get {
                return ResourceManager.GetString("xml-settings-xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dropDowns&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;criminal courts&quot;,
        ///      &quot;query&quot;: &quot;#sbxControlID2&quot;,
        ///      &quot;options&quot;: [
        ///        {
        ///          &quot;id&quot;: 0,
        ///          &quot;name&quot;: &quot;All Probate Courts&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;All JP Courts&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;All CCL Courts&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 3,
        ///          &quot;name&quot;: &quot;JP No. 1&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 4,
        ///          &quot;name&quot;: &quot;JP No. 2&quot;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_tarrantCountyCaseType_json {
            get {
                return ResourceManager.GetString("xml-tarrantCountyCaseType-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dropDowns&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;custom search for courts&quot;,
        ///      &quot;query&quot;: &quot;#sbxControlID2&quot;,
        ///      &quot;options&quot;: [
        ///        {
        ///          &quot;id&quot;: 0,
        ///          &quot;name&quot;: &quot;exclude criminal cases&quot;,
        ///          &quot;query&quot;: &quot;#divOption1 &gt; a&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;include criminal case records&quot;,
        ///          &quot;isDefault&quot;: true,
        ///          &quot;query&quot;: &quot;#divOption2 &gt; a&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;criminal case records only&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_tarrantCountyCustomType_json {
            get {
                return ResourceManager.GetString("xml-tarrantCountyCustomType-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dataPoints&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;CaseStyle&quot;,
        ///      &quot;xpath&quot;: &quot;/html/body/table[3]/tbody/tr/td[1]/b&quot;,
        ///      &quot;result&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;Plantiff&quot;,
        ///      &quot;xpath&quot;: &quot;//th[text()=&apos;State&apos;]&quot;,
        ///      &quot;result&quot;: &quot;&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string xml_tarrantCountyDataPoint_json {
            get {
                return ResourceManager.GetString("xml-tarrantCountyDataPoint-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steps&quot;: [
        ///    {
        ///      &quot;actionName&quot;: &quot;navigate&quot;,
        ///      &quot;displayName&quot;: &quot;open-website-base-uri&quot;,
        ///      &quot;wait&quot;: 1200,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;page&quot;,
        ///        &quot;query&quot;: &quot;https://odyssey.tarrantcounty.com/PublicAccess/default.aspx&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;actionName&quot;: &quot;exists&quot;,
        ///      &quot;displayName&quot;: &quot;case-type-selector&quot;,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;css&quot;,
        ///        &quot;query&quot;: &quot;#sbxControlID2&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;actionName&quot;: &quot;set-select-value&quot;,
        ///      &quot;displayName&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_tarrantCountyMapping_1_json {
            get {
                return ResourceManager.GetString("xml-tarrantCountyMapping-1-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steps&quot;: [
        ///    {
        ///      &quot;actionName&quot;: &quot;navigate&quot;,
        ///      &quot;displayName&quot;: &quot;open-website-base-uri&quot;,
        ///      &quot;wait&quot;: 1200,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;page&quot;,
        ///        &quot;query&quot;: &quot;https://odyssey.tarrantcounty.com/PublicAccess/default.aspx&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;actionName&quot;: &quot;exists&quot;,
        ///      &quot;displayName&quot;: &quot;case-type-selector&quot;,
        ///      &quot;locator&quot;: {
        ///        &quot;find&quot;: &quot;css&quot;,
        ///        &quot;query&quot;: &quot;#sbxControlID2&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;actionName&quot;: &quot;set-select-value&quot;,
        ///      &quot;displayName&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml_tarrantCountyMapping_2_json {
            get {
                return ResourceManager.GetString("xml-tarrantCountyMapping-2-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;court type selections&quot;,
        ///  &quot;step&quot;: {
        ///    &quot;actionName&quot;: &quot;set-select-value&quot;,
        ///    &quot;displayName&quot;: &quot;case-type-selector&quot;,
        ///    &quot;expectedValue&quot;: &quot;1&quot;,
        ///    &quot;locator&quot;: {
        ///      &quot;find&quot;: &quot;css&quot;,
        ///      &quot;query&quot;: &quot;#sbxControlID2&quot;
        ///    }
        ///  },
        ///  &quot;courtMap&quot;: [
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;name&quot;: &quot;Justice of Peace&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 2,
        ///      &quot;name&quot;: &quot;Court Court at Law&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;Probate&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string xml_tarrantCourtSearchDropDown_json {
            get {
                return ResourceManager.GetString("xml-tarrantCourtSearchDropDown-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;webDrivers&quot;: {
        ///    &quot;selectedIndex&quot;: 3,
        ///    &quot;drivers&quot;: [
        ///      {
        ///        &quot;id&quot;: 0,
        ///        &quot;name&quot;: &quot;Chrome&quot;,
        ///        &quot;isVerified&quot;: false
        ///      },
        ///      {
        ///        &quot;id&quot;: 1,
        ///        &quot;name&quot;: &quot;Firefox&quot;,
        ///        &quot;isVerified&quot;: true
        ///      },
        ///      {
        ///        &quot;id&quot;: 2,
        ///        &quot;name&quot;: &quot;Edge&quot;,
        ///        &quot;isVerified&quot;: false
        ///      },
        ///      {
        ///        &quot;id&quot;: 3,
        ///        &quot;name&quot;: &quot;Chrome Legacy&quot;,
        ///        &quot;isVerified&quot;: false
        ///      }
        ///    ]
        ///  }
        ///}.
        /// </summary>
        internal static string xml_webDrivers_json {
            get {
                return ResourceManager.GetString("xml-webDrivers-json", resourceCulture);
            }
        }
    }
}
