# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI .NET Framework

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current version number
      id: versionid
      run: echo "vrsn_number=3.2" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%m%d')" >> "$GITHUB_OUTPUT"
    
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
    
    - uses: browser-actions/setup-firefox@v1
    - run: firefox --version

    - name: Set Release Version
      run: |
          echo "BUILD_VERSION=${{format('{0}.{1}', steps.versionid.outputs.vrsn_number, github.run_number)}}" >> $GITHUB_ENV

    - name: Echo Release Version
      run: echo ${{ env.BUILD_VERSION }}

    - name: Restore Packages
      if: github.event.pull_request.merged == true
      timeout-minutes: 10
      shell: pwsh
      run: |
        & ./pipeline-restore-packages.ps1

    - name: Build solution
      if: github.event.pull_request.merged == true
      timeout-minutes: 5
      shell: pwsh
      run: |
        & ./pipeline-build-solutions.ps1 -version "${{ env.BUILD_VERSION }}"

    - name: Build Presentation solution
      if: github.event.pull_request.merged == true
      timeout-minutes: 5
      shell: pwsh
      run: |
        & ./pipeline-build-presentation.ps1 -version "${{ env.BUILD_VERSION }}"

    - name: Publish MyGet Packages
      if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
      shell: pwsh
      run: |
        & ./publish-nuget.ps1 -apikey "${{ secrets.MY_GET_ACCESS_KEY }}" -publishurl "${{ secrets.MY_GET_PUBLISH_URL }}"

