# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'CI: Build and Publish : Core Components'

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

env:
    LEGALLEAD_INSTALLATION_KEY: ${{ secrets.LEGALLEAD_INSTALLATION_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%m%d')" >> "$GITHUB_OUTPUT"

    # chrome driver is needed for some unit tests
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
  
    # firefox driver is needed for some unit tests
    - uses: browser-actions/setup-firefox@v1
    - run: firefox --version

    - name: Set Release Version
      run: |
          echo "BUILD_VERSION=${{format('{0}.{1}', vars.LEGALLEAD_VERSION_PREFIX, github.run_number)}}" >> $GITHUB_ENV

    - name: Echo Release Version
      run: echo ${{ env.BUILD_VERSION }}

    - name: Build solution
      if: github.event.pull_request.merged == true
      timeout-minutes: 5
      shell: pwsh
      run: |
        & ./pipeline-build-solutions.ps1 -version "${{ env.BUILD_VERSION }}"

    - name: Publish MyGet Packages
      if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
      shell: pwsh
      run: |
        & ./publish-nuget.ps1 -apikey "${{ secrets.MY_GET_ACCESS_KEY }}" -publishurl "${{ secrets.MY_GET_PUBLISH_URL }}"

