# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'CI : Build and Deploy : Windows UI'
on:
  push:
    branches:  
      - '**/presentation**'        # matches every branch
      - 'main'   # excludes master
    paths:
      - 'src/presentation/legallead.desktop/**'
env:
    FAILED_TEST_COUNT: "0"

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4  
    - name: Set Release Version
      shell: bash
      run: |
          echo "BUILD_VERSION=${{format('{0}.{1}', vars.LEGALLEAD_VERSION_PREFIX, github.run_number)}}" >> $GITHUB_ENV

    - name: Build Presentation solution
      timeout-minutes: 5
      shell: pwsh
      run: |
        & ./pipeline-build-presentation.ps1 -version "${{ env.BUILD_VERSION }}"

    - name: Publish MyGet Packages
      if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
      shell: pwsh
      run: |
        & ./publish-nuget.ps1 -apikey "${{ secrets.MY_GET_ACCESS_KEY }}" -publishurl "${{ secrets.MY_GET_PUBLISH_URL }}"
