# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Presentation Build
on:
  push:
    branches:  
      - '**'        # matches every branch
      - '!main'   # excludes master
env:
    FAILED_TEST_COUNT: "0"

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4  
    - name: Set Release Version
      shell: bash
      run: |
          echo "BUILD_VERSION=${{format('{0}.{1}', vars.LEGALLEAD_VERSION_PREFIX, github.run_number)}}" >> $GITHUB_ENV

    - name: Build Presentation solution
      timeout-minutes: 5
      shell: pwsh
      run: |
        & ./pipeline-build-presentation.ps1 -version "${{ env.BUILD_VERSION }}"
