# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CQ .NET Framework
on:
  push:
    branches:  
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
      # Repository name with owner. For example, actions/checkout
      # Default: ${{ github.repository }}
        repository: '${{ github.repository }}'

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
      if: github.event_name != 'pull_request'
    
    - uses: browser-actions/setup-firefox@v1
    - run: firefox --version
      if: github.event_name != 'pull_request'
  
    - name: Restore Packages
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: |
        & ./pipeline-restore-packages.ps1

    - name: Build solution
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: |
        & ./pipeline-build-solutions.ps1 -version "${{ env.BUILD_VERSION }}"

    - name: Test with dotnet
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: |
        & ./pipeline-test-solutions.ps1

    - name: Summarize Test Results
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: |
        & ./pipeline-summarize-tests.ps1 -workingDir "${{ github.workspace }}"

    - name: Upload dotnet test results
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ~/**/*.trx
