# This workflow will build a .NET framework project(s)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# this build runs for every push where a change to src directory is included
name: 'CQ : Build and Test : Permissions API'
on:
  push:
    branches:  
      - '**'            # matches every branch
      - '!main'         # excludes master
      - '!releases'     # excludes releases
    paths:
      - 'src/api/legallead.permissions.api/**'
      - 'src/api/permissions.api.tests/**'

env:
  NET_VERSION: '6.0.x'
  LEGALLEAD_INSTALLATION_KEY: ${{ secrets.LEGALLEAD_INSTALLATION_KEY }}
  SOLUTION_NAME: ${{ github.workspace }}/src/api/legallead.api.sln
  PROJECT_NAME: ${{ github.workspace }}/src/api/permissions.api.tests/permissions.api.tests.csproj

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}

    - name: Unit Test with dotnet
      run: dotnet test ${{ env.PROJECT_NAME }} --logger trx --results-directory "TestResults-${{ env.NET_VERSION }}"

    - name: Launch API Instance
      timeout-minutes: 10
      shell: pwsh
      run: |
        & ./x-test-api-integration.ps1
      
    - name: Postman Testing
      uses: matt-ball/newman-action@master
      with: 
        collection: ${{ github.workspace }}/postman/ll-authorizations.postman_collection.json
        environment: ${{ github.workspace }}/postman/LL-LOCAL.postman_environment.json

    - name: Stop API Instance
      shell: pwsh
      if: ${{ always() }}
      run: |
        [System.Diagnostics.Process]::GetProcessesByName('legallead.permissions.api') | ForEach-Object { $_.Kill() }

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with: 
        name: dotnet-results-permissions-api-${{ env.NET_VERSION }}
        path: TestResults-${{ env.NET_VERSION }}