# ./leads-ui/.github/workflows/release-branch-restriction.yml
name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'releases' && github.head_ref != 'main'
        run: |
          echo "ERROR: You can only merge to releases from main."
          exit 1